{
 "title": "SLO Detailed",
 "tags": [ "SLO, SRE" ],
 "time": { "from": "now-20m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "slo_version",
    "query": {
     "query": "label_values(slo:violation_ratio_threshold{}, slo_version)"
    }
   },
   {
    "name": "slo_domain",
    "query": {
     "query": "label_values(slo:violation_ratio_threshold{slo_version=\"$slo_version\"}, slo_domain)"
    }
   },
   {
    "name": "slo_type",
    "query": {
     "query": "label_values(slo:violation_ratio{slo_version=\"$slo_version\", slo_domain=\"$slo_domain\"}, slo_type)"
    }
   },
   {
    "name": "slo_class",
    "query": {
     "query": "label_values(slo:violation_ratio_threshold{slo_version=~\"$slo_version\", slo_domain=~\"$slo_domain\", slo_type=~\"$slo_type\"}, slo_class)"
    }
   },
   { "name": "slo_time_range", "query": { "query": "label_values(slo_time_range)" } },
   {
    "name": "latency_slo_type",
    "query": {
     "query": "label_values(slo:violation_ratio_threshold{slo_version=\"$slo_version\", slo_domain=\"$slo_domain\", slo_type=~\"$slo_type\", slo_type=~\".*latency.*\"}, slo_type)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(slo:violation_ratio_threshold{slo_version=\"$slo_version\", slo_domain=\"$slo_domain\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "ON CALL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Responsible team",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "displayType": "Regular",
     "expr": "max(slo:stable_version{slo_domain=\"$slo_domain\",slo_version=\"$slo_version\"}) by (team)",
     "legendFormat": "{{team}}",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Shadow (non-working hours) escalation",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "displayType": "Regular",
     "expr": "max(slo:stable_version{slo_domain=\"$slo_domain\",slo_version=\"$slo_version\"}) by (escalate)",
     "legendFormat": "{{escalate}}",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  { "title": "$slo_type", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "slo_type" },
  {
   "title": "$slo_type $slo_class",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "repeat": "slo_class",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - max_over_time(slo:violation_ratio{slo_domain=\"$slo_domain\", slo_type=~\"$slo_type\", slo_class=\"$slo_class\", slo_version=\"$slo_version\", slo_time_range=\"$slo_time_range\", namespace=\"$namespace\"}[5m])"
    }
   ]
  },
  { "title": "Error budget", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "error budget for $slo_class slo class",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 58 },
   "repeat": "slo_class",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "0", "legendFormat": "zero" },
    {
     "expr": "max_over_time(slo:violation_ratio{slo_domain=\"$slo_domain\", slo_type=~\"$slo_type\", slo_class=\"$slo_class\", slo_version=\"$slo_version\", slo_time_range=\"$slo_time_range\", namespace=\"$namespace\"}[15m])\n/ on (slo_class,slo_domain,slo_version, slo_type, namespace) group_left ()\n(\n    slo:violation_ratio_threshold - 1\n)\n+1",
     "legendFormat": "{{ slo_type }}"
    }
   ]
  },
  {
   "title": "$slo_type thresholds (as %)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "repeat": "slo_type",
   "collapsed": true,
   "panels": [
    {
     "title": "$slo_type $slo_class",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 22 },
     "repeat": "slo_class",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "slo:violation_ratio_threshold{slo_class=\"$slo_class\",slo_domain=\"$slo_domain\",slo_version=\"$slo_version\", slo_type=\"$slo_type\", namespace=\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "$latency_slo_type thresholds (as duration)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 287 },
   "repeat": "latency_slo_type",
   "collapsed": true,
   "panels": [
    {
     "title": "$latency_slo_type percentile threshold for $slo_class",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 29 },
     "repeat": "slo_class",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "slo:violation_ratio_threshold{slo_class=\"$slo_class\",slo_domain=\"$slo_domain\",slo_version=\"$slo_version\", slo_type=\"$latency_slo_type\", namespace=\"$namespace\"}"
      }
     ]
    }
   ]
  }
 ]
}