{
 "title": "SLO exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "module",
    "query": "label_values({__name__=~\"(slo_exporter_)?event_processing_duration_seconds_count\",instance=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\"},module)  "
   },
   {
    "name": "matcher_type",
    "query": "label_values(slo_exporter_dynamic_classifier_matcher_operation_duration_seconds_count,matcher_type)"
   },
   {
    "name": "cluster",
    "query": "label_values(process_start_time_seconds{app=\"slo-exporter\"}, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(process_start_time_seconds{app=\"slo-exporter\", cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "instance",
    "query": "label_values(app_build_info{app=\"slo-exporter\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, instance)"
   },
   { "name": "log_filter" }
  ]
 },
 "panels": [
  { "title": "Reources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{app=~\"slo-exporter.*\", instance=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\"}",
     "legendFormat": "{{cluster}}/{{namespace}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Used CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{app=~\"slo-exporter.*\", instance=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "{{cluster}}/{{namespace}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Number of gorutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{app=~\"slo-exporter.*\", instance=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\"}",
     "legendFormat": "{{cluster}}/{{namespace}}/{{instance}}"
    }
   ]
  },
  { "title": "Nginx log tailer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Number of read lines/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(slo_exporter_tailer_lines_read_total{instance=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "{{cluster}}/{{namespace}}/{{instance}}"
    },
    {
     "expr": "sum(rate(slo_exporter_tailer_lines_read_total{instance=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Size of remaining file part to be tailed (delay)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "slo_exporter_tailer_file_size_bytes{instance=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\"} - slo_exporter_tailer_file_offset_bytes{instance=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\"}",
     "legendFormat": "{{cluster}}/{{namespace}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Size of already tailed logs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "slo_exporter_tailer_file_offset_bytes{instance=~\"$instance\", cluster=~\"$cluster\", namespace=~\"$namespace\"}",
     "legendFormat": "{{cluster}}/{{namespace}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Number of malformed lines",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(slo_exporter_tailer_malformed_lines_total{instance=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\"}[1m]) > 0",
     "legendFormat": "{{cluster}}/{{namespace}}/{{instance}}"
    }
   ]
  },
  { "title": "Prometheus Ingester", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Number of Prometheus API calls in last 1m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(slo_exporter_prometheus_ingester_query_duration_seconds_count{instance=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\"}[1m])) by (query_type)",
     "legendFormat": "{{query_type}}"
    }
   ]
  },
  {
   "title": "Histogram heatmap of Prometheus query duration per second",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(slo_exporter_prometheus_ingester_query_duration_seconds_bucket{instance=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\"}[1m])) by (query_type,le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(slo_exporter_prometheus_ingester_query_fails_total{instance=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\"}[1m]) > 0",
     "legendFormat": "{{cluster}}/{{namespace}}/{{instance}} {{type}}"
    }
   ]
  },
  { "title": "Pipeline duration histogram", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "$module processing duration histogram per second",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 2.4, "x": 0, "y": 28 },
   "repeat": "module",
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"(slo_exporter_)?event_processing_duration_seconds_bucket\",module=\"$module\", instance=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Event filter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Filtered events by metadata key/s",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(slo_exporter_event_filter_filtered_events_total{instance=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\"}[1m])) by (metadata_key)",
     "legendFormat": "{{metadata_key}}"
    }
   ]
  },
  { "title": "Relabel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Dropped events in relabeling /s",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(slo_exporter_relabel_dropped_events_total{instance=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\"}[1m])) by (metadata_key)",
     "legendFormat": "dropped events"
    }
   ]
  },
  { "title": "Dynamic classifier", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Events classified by matchers or unclassified in 1m",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(slo_exporter_dynamic_classifier_events_processed_total{instance=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\"}[1m])) by (result, classified_by)",
     "legendFormat": "{{result}} by {{classified_by}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(slo_exporter_dynamic_classifier_errors_total{instance=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "{{cluster}}/{{namespace}}/{{instance}} {{type}}"
    }
   ]
  },
  {
   "title": "Histogram heatmap of $matcher_type macther operations duration per second",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 52 },
   "repeat": "matcher_type",
   "targets": [
    {
     "expr": "sum(rate(slo_exporter_dynamic_classifier_matcher_operation_duration_seconds_bucket{matcher_type=\"$matcher_type\", instance=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Statistical classifier", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Weights per classification",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(slo_exporter_statistical_classifier_classification_weight{app=~\"slo-exporter.*\", instance=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\"}) by (slo_class, slo_domain)",
     "legendFormat": "{{slo_domain}}/{{slo_class}}"
    }
   ]
  },
  {
   "title": "Number of procesed events/s by result",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(slo_exporter_statistical_classifier_events_processed_total{app=~\"slo-exporter.*\", instance=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\"}[1m])) by (result)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Number of errors by type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(slo_exporter_statistical_classifier_errors_total{app=~\"slo-exporter.*\", instance=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "SLO event producer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Histogram heatmap of event evaluation duration per second",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum(rate(slo_exporter_slo_event_producer_evaluation_duration_seconds_bucket{instance=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Number of events not matching any rule",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(slo_exporter_slo_event_producer_events_not_matching_any_rule{instance=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\"}[1m]) > 0",
     "legendFormat": "{{cluster}}/{{namespace}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Number of unclassified events",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(slo_exporter_slo_event_producer_unclassified_events_total{instance=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\"}[1m]) > 0",
     "legendFormat": "{{cluster}}/{{namespace}}/{{instance}} "
    }
   ]
  },
  { "title": "Prometheus exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Number of unique keys per app",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "count(sum(slo_domain_slo_class_slo_app_event_key:slo_events_total{instance=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\"}) by (slo_app,event_key)) by (slo_app)",
     "legendFormat": "{{cluster}}/{{namespace}}/{{instance}} {{slo_app}}"
    }
   ]
  },
  {
   "title": "Remaining number of unique event keys",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(slo_exporter_prometheus_exporter_event_keys_limit{instance=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\"} - slo_exporter_prometheus_exporter_event_keys{instance=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\"}) by (cluster,namespace,instance)",
     "legendFormat": "{{cluster}}/{{namespace}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(slo_exporter_prometheus_exporter_errors_total{instance=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Dropped events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Dropped unclassified events",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "{container_name=\"slo-exporter\", pod_name=~\"$instance\", namespace=~\"$namespace\", cluster=~\"$cluster\", instance !~\".*sorry-page.*\"} |= \"unable to classify\""
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "{container_name=\"slo-exporter\", pod_name=~\"apiproxy-0|apiproxy-1|apiproxy-2|sorry-page-apiproxy-0|sorry-page-apiproxy-1|sorry-page-userproxy-0|sorry-page-userproxy-1|userproxy-0|userproxy-1|userproxy-2\", namespace=~\"sklik-production\", node_name=~\".*.*.*\"} |= \"\""
    }
   ]
  }
 ]
}